# User setting
twitter_username: jschnatterer
github_username: schnatterer
stackoverflow_userid: 1845976
linkedin_personal_url: johannes-schnatterer
xing_profile: Johannes_Schnatterer
keybase_id: schnatterer

copyright: Johannes Schnatterer

blog_url: 'https://itaffinity.wordpress.com/'
publications_url: '/publications'
talks_url: '/talks'
projects_url: '/projects'

blog_text: IT affinity - my personal blog (external link)
publications_text: Articles I published in journals and on other sites
talks_text: A list of public talks I gave
projects_text: A excerpt of FOSS projects I started or contributed to

# Build settings
markdown: kramdown