# User setting
mastodon_handle: floss.social/@schnatterer
bluesky_username: schnatterer.info
github_username: schnatterer
stackoverflow_userid: 1845976
linkedin_personal_url: jschnatterer
xing_profile: Johannes_Schnatterer
keybase_id: schnatterer

calender_url: https://platform.cloudogu.com/person/johannes-schnatterer/

copyright: Johannes Schnatterer

publications_url: 'publications'
talks_url: 'talks'
projects_url: 'projects'

languages: ["en", "de" ]
languageNames:
  en: English
  de: Deutsch
exclude_from_localizations: ["font-awesome", "img", "css", "javascript", "CNAME", "favicon.ico", "site.webmanifest", ".well-known"]

# Build settings
markdown: kramdown

exclude:
  - LICENSE
  - README.md
  # Needed for GH action
  - vendor
include:
  - .well-known
