# User setting
twitter_username: jschnatterer
mastodon_handle: floss.social/@schnatterer
github_username: schnatterer
stackoverflow_userid: 1845976
linkedin_personal_url: jschnatterer
xing_profile: Johannes_Schnatterer
keybase_id: schnatterer

copyright: Johannes Schnatterer

blog_url: 'https://itaffinity.wordpress.com/'
publications_url: 'publications'
talks_url: 'talks'
projects_url: 'projects'

languages: ["en", "de" ]
languageNames:
  en: English
  de: Deutsch

# Build settings
markdown: kramdown

include:
  - .well-known
