# User setting
twitter_username: jschnatterer
mastodon_handle: floss.social/@schnatterer
github_username: schnatterer
stackoverflow_userid: 1845976
linkedin_personal_url: johannes-schnatterer
xing_profile: Johannes_Schnatterer
keybase_id: schnatterer

copyright: Johannes Schnatterer

blog_url: 'https://itaffinity.wordpress.com/'
publications_url: '/publications'
talks_url: '/talks'
projects_url: '/projects'

blog_text: IT affinity - personal blog (external link)
publications_text: Articles published in journals and on blogs
talks_text: A list of public speaking engagements
projects_text: An excerpt of contributions to FOSS projects

# Build settings
markdown: kramdown