name: Update projects and posts

on:
  schedule:
    - cron:  '0 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y jq
      - run: sudo -H pip install yq
      - uses: actions/checkout@v4
      - run: _data/scripts/update-projects.sh ${{ secrets.PAT }}
      - run: _data/scripts/sort-projects.sh
      - run: _data/scripts/update-posts.sh
      - run: _data/scripts/sort-posts.sh
      - run: _data/scripts/update-pinned-projects.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updates projects and posts
